### ISSUE TITLE
Created zip's under Windows are corrupt

### ISSUE THREAD

**Issue by blakemcbride** [cthackers/adm-zip#130]
I did the following to create a zip file:

```
var zip = new AdmZip();
zip.addLocalFolder(dir);
zip.writeZip(zipfilename);
```

It worked fine under Linux & Mac but the zip file had garbage under Windows.

**Comment by neocotic** [comment]
I'm also seeing this, which is strange as I know this used to work fine and suddenly, within the last month, it's breaking. I'm assuming due to problems with the latest release.

ZIP tools (including Window's own) are treating the files that I added as folders. The size of the ZIP file is as I'd expect, but the entries are no longer being added correctly. Could this be related to the recent changes I've seen related to `attr` for entries?

**Comment by tobaiasjl** [comment]
> ZIP tools (including Window's own) are treating the files that I added as folders.

also have this problem...

**Comment by adenhertog** [comment]
I'm getting the same issue. Windows 8.1, zip files appear empty though they are the expected size. Rolling back to v0.4.4 works for me.

**Comment by houssemFat** [comment]
I confirm, all files are converted to empty folders (Windows 8.1)

**Comment by teu** [comment]
Hi, getting this problem under Ubuntu Linux too.

**Comment by rajojon23** [comment]
not working for me as well in Windows 8.1 (corrupted file message)

**Comment by houssemFat** [comment]
the @adenhertog solution works for me also, consider Rolling back to v0.4.4

**Comment by blakemcbride** [comment]
Since the author won't fix the problem, I fixed it by switching to zip-folder.  That works flawlessly on Linux, Mac & Windows.

**Comment by tobaiasjl** [comment]
Jap, you guys should switch to an other zipper. I successfuly changed to https://github.com/archiverjs/node-archiver

**Comment by theo-armour** [comment]
thanks @blakemcbride, zip-folder works for me, though slightly inconvenient for me as I have to create a directory first. 

Still using adm-zip to extract files. Would be nice to see this issue fixed...

**Comment by lloiser** [comment]
this issue is actually fixed with eb9291015540bc11157494d384e020cd16cfcaf4
unfortunately 06e1f6853acd97897ba3fd7928a379a71731d01f breaks this lib again if you call `addLocalFolder` it again. I have fixed this problem with my pull request.
So we only have to wait for my pull request to get merged and a new version pushed to npm

**Comment by bengle** [comment]
@ blakemcbride, Thanks,it works well!

**Comment by jdrake** [comment]
Thanks @ninjaonsafari that worked for me. Took like a minute to swap out.

**Comment by urish** [comment]
Also faced this issue, ended up using [archiver](https://github.com/archiverjs/node-archiver) instead.
