### ISSUE TITLE
How does ADM-Zip remove occupancy

### ISSUE THREAD

**Issue by songyizhe** [cthackers/adm-zip#366]
When I use the ExtractallTo method, I need to delete the ZIP package when it is completed, and the FS module is used to delete the FS prompt that the ZIP file is deleted successfully, but the ZIP file is still there, and the program needs to be closed or refreshed before it disappears. Could you please tell me how ADM-ZIP can be removed after use?

**Comment by roosipuu** [comment]
what ADM-ZIP does is, it caches file into memory. Even if you delete file it stays in memory.
```javascript
let zip = new AdmZip("./my_file.zip");
```
you could delete reference to content like:
```javascript
zip = null;
```
or use scoped variables
```javascript
if (true) {
  const zip = new AdmZip("./my_file.zip");
  zip.ExtractallTo(...)
}
// delete "zip" variable
```
after exiting block, "zip" variable will be deleted automatically.

_Note: if you use **var** keyword (instead of **const** or **let**). Variable stays in memory._
