### ISSUE TITLE
extractAllToAsync isn't done unzipping when callback is triggered

### ISSUE THREAD

**Issue by sebastianrath** [cthackers/adm-zip#388]
I am using `adm-zip` to extract a zip file that is 100 MB in size. I noticed that `extractAllToAsync` isn't done with extracting, although the callback is executed without an error.

```
      zip.extractAllToAsync(dstProject, true, (error: Error) => {
        if (error) {
          reject(error);
        } else {
          resolve(); <--- breakpoint here and some files are not extracted yet.
        }
      });
```

Only `extractAllTo` works as expected though. Any ideas, or am I onto a bug here? For clarification, this seems to be a severe timing issue as I can only reproduce this every x'th time

**Comment by BrianBothwell** [comment]
This is causing my CI/CD scripts to fail! Please fix.

**Comment by seb-mtl** [comment]
@BrianBothwell Just to be sure you didn't miss my workaround. Since you need to touch your CI anyway, either with a bump or fix, you can use `extractAllTo` instead of `extractAllToAsync` in the meantime

**Comment by BrianBothwell** [comment]
This is still failing for me with 0.5.9. Is @5saviahv's fix included in that release?

**Comment by sysrage** [comment]
Has this package been abandoned? Issues don't seem to be getting resolved, even when fixes are submitted as PRs.

**Comment by BrianBothwell** [comment]
Has this package been abandoned? Issues don't seem to be getting resolved, even when fixes are submitted as PRs.

**Comment by KirrsGool** [comment]
> although the callback is executed without an error

This may be because the callback is not triggered, try this https://github.com/cthackers/adm-zip/issues/407#issuecomment-990086783

**Comment by sysrage** [comment]
Safe to assume this package is abandoned? This issue still exists with the currently-released package.

**Comment by sysrage** [comment]
> @BrianBothwell Just to be sure you didn't miss my workaround. Since you need to touch your CI anyway, either with a bump or fix, you can use `extractAllTo` instead of `extractAllToAsync` in the meantime

FYI, this doesn't actually work either, @seb-mtl. As a last-ditch attempt, I did try `.extractAllTo()` and even that is returning before the extraction is complete. Easy to reproduce by wrapping it in a promise or simply having a node script do nothing but extract the file then log something to console. you'll notice that the console log shows up, then your app sits there for awhile before actually exiting. That's because the extraction is still happening. Once extraction actually completes, the app exits (or promise resolves).
