### ISSUE TITLE
writeZip() throws "Invalid LOC header (bad signature)" error

### ISSUE THREAD

**Issue by hyperlink** [cthackers/adm-zip#64]
This issue is occurring in version: 0.4.3 on Windows.

Initially noticed this occurred with jar files however I can reproduce it with other zips I had.

Examples:
The kickstarter zip: http://www.99lime.com/downloads/
Apache tomcat zip: http://tomcat.apache.org/download-80.cgi

``` javascript
var AdmZip = require('adm-zip');
var jarZip = new AdmZip('WEB-INF\\lib\\snappy-java.jar');
jarZip.writeZip();
```

Produces

```
A:\myapp\node_modules\adm-zip\headers\entryHeader.js:113
                throw Utils.Errors.INVALID_LOC;
                                  ^
Invalid LOC header (bad signature)
```

**Comment by rtm** [comment]
Is there some reason this ticket was closed?
I'm experiencing the same problem.
Any work-arounds?

**Comment by BiteBit** [comment]
Same thing here.

zf = new AdmZip './Blog.zip'
entry = zf.getEntry(Blog/manifest.json')
zf.deleteFile entry
zf.writeZip()

then throw error

**Comment by bigmeech** [comment]
Has this been fixed? What is the status of this problem?

**Comment by AndrePessoa** [comment]
After some days studinng to understand how the zip really works I have some ideias: 

Can be the header class broking the zip because it is using both headers ( at file and at header ) as the same, and mixing values like extraLen that can have diferent values? I´m doing some tests and create a little ZIP lint to test the file state, but I dont have a final answer. Anyone know more about this?

**Comment by alonweissfeld** [comment]
@bigmeech +1.
Has this been fixed? I'm getting **Invalid LOC header (bad signature)** when trying:
```
var AdmZip = require( 'adm-zip' );
var zip = new AdmZip( "./archive.zip" );
zip.toBuffer( function ( buf ) {
    console.log( 'success?', buf );
}, function ( err ) {
    console.log( 'error', err );
});
```
However the buffer prints out. Any updates here?

**Comment by dcrockwell** [comment]
+1 This is still an issue.

**Comment by neutrinog** [comment]
Using adm-zip v0.4.7 on node v5.3.0. This is still an issue.

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <Re: [adm-zip] writeZip() throws "Invalid LOC header (bad signature)" error (#64)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by homeation** [comment]
This is still an error. node 5.5.0.
Any word on a fix?

**Comment by AndrePessoa** [comment]
Guys,

I tried to fix this and submited my version here: https://github.com/cthackers/adm-zip/pull/159 ... It is working to me in a project where I zip, unzip, write and update lots of times.

This bug, and some others, were because the code mix all headers as the same object and try to manipulate it properly, but fails sometimes.

I hope it is useful

**Comment by rolatsch** [comment]
Any updates here? 
@AndrePessoa can i somehow use your fix right now.

**Comment by AndrePessoa** [comment]
@rolatsch, do you can use this files is you can: 
https://github.com/cthackers/adm-zip/pull/159/files

Im using this at my projects and is working fine.

**Comment by rolatsch** [comment]
@AndrePessoa  i have tried to replace my files with the changed ones but now i get TypeError: undefined is not a function at Object.module.exports.crc32 (TdT\node_modules\adm-zip\util\utils.js:71:62) 
May i get a working package of this module anywhere?

**Comment by WouterDeKort** [comment]
@AndrePessoa any updates on this? I'm still having this error

**Comment by blazer82** [comment]
There's a workaround by migrating all entries to a new zip file (example in coffeescript):
```
existingZip = new Zip path
newZip = new Zip

for entry in xlsxZip.getEntries()
	if iWantToChangeThisFile
		content = change xlsxZip.readAsText entry, 'utf-8'
		buffer = new Buffer content, 'utf-8'
		newZip.addFile entry.entryName, buffer
	else
		newZip.addFile entry.entryName, xlsxZip.readFile entry

newZip.writeZip newPath
```

**Comment by basvanmeurs** [comment]
Same problem here. When you parse a zip (with folders) and then try to compress it again I get the 'Invalid LOC Header' error.

My workaround: use the archiver npm module and convert like this:
`            var archiver = require('archiver');
            var archive = archiver('zip');

            archive.on('error', function(err) {
                throw err;
            });

            archive.pipe(response);

            response.writeHead(200, {
                'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            });

            var entries = zip.getEntries();
            for (var i = 0, n = entries.length; i < n; i++) {
                if (!entries[i].isDirectory) {
                    var data = entries[i].getData();
                    archive.append(data, {name: entries[i].entryName});
                }
            }
            archive.finalize();
`

**Comment by AdrianoFerrari** [comment]
FYI:
I used adm-zip because it seemed to be one of the few js libraries that allowed one to add files to existing zips.

However, I kept hitting this error, so I switched to JSZip. Works just fine for my use case (add a dynamically generated text file to an existing zip, and stream zip to user with node Express server).

**Comment by vhogemann** [comment]
Have the same issue invoking the .toBuffer() method with macOS generated zip-files.

**Comment by plettix** [comment]
I got this error calling toBuffer() in nodejs 6.10.0

**Comment by AlexandreKilian** [comment]
Don't expect this to be fixed, this has been an issue for 5 years now and there hasn't even been a reaction from the maintainer… I switched to JSZip and I got it working fine with that + fs for reading, writing:

https://stuk.github.io/jszip/


```js

saveFile(file, data, json = true) {
        return new Promise((resolve, reject) => {
            const contents = json ? JSON.stringify(data) : data;
            this.document.file(`${file}.json`, contents);
            let promise;
            if (Zip.support.uint8array) {
                promise = this.document.generateAsync({type : "uint8array"});
              } else {
                promise = this.document.generateAsync({type : "string"});
              }

            promise.then((blob) => {
                fs.writeFile(this.file, blob, ()=>{
                    resolve(true);
                });
            });
        });
    }

    getFile(file, json = true) {
        return new Promise((resolve, reject) => {
            try {
                let f;
                if(f = this.document.file(`${file}.json`)){
                    f.async("string").then((contents) => {
                        resolve(json ? JSON.parse(contents) : contents);
                });
                } else {
                    //FILE NOT FOUND
                }
            } catch (e) {
                //DIFFERENT ERROR
            }
        })
    }

```

Ignore all the stuff around it, this.document is my JSZip object

**Comment by LloydFranklinSmith** [comment]
I found a workaround (I use Node on Windows):
The error occurred whenever i tried updating multiple files using a single instance of adm zip and stoped occurring when I used a new instance of adm zip for every change.
instead of
`doZippyThings{
....
this.zipfile.writeZip(...);
}`
I now use
`doZippyThings(){
var zipFile = new AdmZip(...);
...
.zipfile.writeZip(...);
}`
Hope this helps some lost code crusaders.

**Comment by nassau-t** [comment]
You're wrong. I also failed with the same error.
You can change several times the zip content, but save it only once.

Example:

```
const AdmZip = require("adm-zip");

function changeFile(fileName) {
  const zip = new AdmZip(fileName);
  const zipEntries = zip.getEntries();
  let changed= false;
  for (const e of zipEntries) {
    if (!e.isDirectory && e.entryName.match(/^.*\.txt$/i)) {
      const string1 = e.getData().toString('utf8');
      const string2 = string1.replaceAll(/aaaa/ig, 'bbbb');
      if (string1 !== string2) {
        changed= true;
        e.setData(Buffer.from(string2, "utf8"));
      }
    }
  }
  if (changed) {
    zip.writeZip(fileName);
  }
  return changed;
}
```

**Comment by 5saviahv** [comment]
If it is still a issue it is really hard to to do anything to fix it. Since no one is willing to providing any information about issue.

I use library a daily and without issues. My **wild guess** would be - it may be caused by some zip64 features what is not fully implemented in ADM-ZIP.

If anyone is willing to `provide .zip file` where it happens. It would be great help.

**Comment by 5saviahv** [comment]
I was able to replicate error with zip found on OP provided Apache tomcat link. Needs some investigation.

**Comment by nassau-t** [comment]
Ok, I understand.

I add a .zip file and a .js.txt file (rename .txt to .js because I can't attach a .js file)

If you execute it, you get:

>node modifyZip.js
filezip/
filezip/carpeta1/
filezip/carpeta1/fems.bat
filezip/carpeta1/index1.sas
changed. modified
changed. save
filezip/carpeta2/
filezip/carpeta2/index2.fems
filezip/carpeta2/index2.sas
C:\sites\proves_node\node_modules\adm-zip\headers\entryHeader.js:184
                throw new Error(Utils.Errors.INVALID_LOC);
                ^

Error: Invalid LOC header (bad signature)
    at Object.loadLocalHeaderFromBinary (C:\sites\proves_node\node_modules\adm-zip\headers\entryHeader.js:184:23)
    at getCompressedDataFromZip (C:\sites\proves_node\node_modules\adm-zip\zipEntry.js:19:24)
    at decompress (C:\sites\proves_node\node_modules\adm-zip\zipEntry.js:49:30)
    at Object.getData (C:\sites\proves_node\node_modules\adm-zip\zipEntry.js:268:24)
    at Object.<anonymous> (C:\sites\proves_node\modifyZip.js:9:23)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)

Node.js v22.3.0
[filezip.zip](https://github.com/user-attachments/files/15858873/filezip.zip)
[modifyZip.js.txt](https://github.com/user-attachments/files/15858877/modifyZip.js.txt)

**Comment by 5saviahv** [comment]
@nassau-t thanks for sharing 

I was able to generate this error very reliably with this:

```javascript
const AdmZip = require('adm-zip');
const {join: joinpath} = require('path');

function changeFile(fileName) {
    const zip = new AdmZip(fileName);

    zip.writeZip(fileName + '.zip');
    zip.writeZip(fileName + '.zip' + '.zip');
}

var xsrc = './apache-tomcat-8.5.100-src.zip';
var xsrc = './filezip.zip';

changeFile(joinpath(__dirname, xsrc));

```
It seems calling `writeZip` pollutes original buffer.

writeZip uses `toBuffer` on the background most likely issue is there.

**Comment by 5saviahv** [comment]
ok, it seems to be something what may need some fundamental update later, but I think I am able to fix it on repo.

### What happens is:
1. During compression we calculate new offsets for each file and update **entry**.
2. We are able to get binary headers for **new** compressed file. 
3. Calling compressToBuffer second time we still use **original Buffer** for getting content. 
4. And updated offsets are no longer valid.
